"""Add OAuth fields to users table

Revision ID: 12159fb7ca28
Revises: d23c18f82103
Create Date: 2025-09-27 04:37:09.229323

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '12159fb7ca28'
down_revision = 'd23c18f82103'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_follows_follower_followed', table_name='follows')
    op.drop_index('idx_follows_status_created_at', table_name='follows')
    op.alter_column('posts', 'post_type',
               existing_type=postgresql.ENUM('daily', 'photo', 'spontaneous', name='posttype'),
               type_=sa.Enum('daily', 'photo', 'spontaneous', name='posttype', schema='public'),
               existing_nullable=False,
               existing_server_default=sa.text("'daily'::posttype"))
    op.drop_index('idx_posts_created_at_desc', table_name='posts')
    op.drop_index('idx_posts_engagement_created_at', table_name='posts')
    op.drop_index('idx_posts_hearts_count', table_name='posts')
    op.drop_index('idx_posts_public_created_at', table_name='posts')
    op.drop_index('idx_posts_reactions_count', table_name='posts')
    op.drop_index('idx_posts_shares_count', table_name='posts')
    op.drop_index('idx_posts_type_created_at', table_name='posts')
    op.drop_index('idx_posts_user_created_at', table_name='posts')
    op.drop_index('idx_user_interactions_created_at_desc', table_name='user_interactions')
    op.drop_index('idx_user_interactions_target_created_at', table_name='user_interactions')
    op.drop_index('idx_user_interactions_type_created_at', table_name='user_interactions')
    op.drop_index('idx_user_interactions_user_created_at', table_name='user_interactions')
    op.add_column('users', sa.Column('oauth_provider', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('oauth_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('oauth_data', sa.JSON(), nullable=True))
    op.drop_index('idx_users_last_feed_view', table_name='users')
    op.create_index(op.f('ix_users_oauth_id'), 'users', ['oauth_id'], unique=False)
    op.create_index(op.f('ix_users_oauth_provider'), 'users', ['oauth_provider'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_oauth_provider'), table_name='users')
    op.drop_index(op.f('ix_users_oauth_id'), table_name='users')
    op.create_index('idx_users_last_feed_view', 'users', ['last_feed_view'], unique=False)
    op.drop_column('users', 'oauth_data')
    op.drop_column('users', 'oauth_id')
    op.drop_column('users', 'oauth_provider')
    op.create_index('idx_user_interactions_user_created_at', 'user_interactions', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_user_interactions_type_created_at', 'user_interactions', ['interaction_type', 'created_at'], unique=False)
    op.create_index('idx_user_interactions_target_created_at', 'user_interactions', ['target_user_id', 'created_at'], unique=False)
    op.create_index('idx_user_interactions_created_at_desc', 'user_interactions', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_posts_user_created_at', 'posts', ['author_id', 'created_at'], unique=False)
    op.create_index('idx_posts_type_created_at', 'posts', ['post_type', 'created_at'], unique=False)
    op.create_index('idx_posts_shares_count', 'posts', ['shares_count'], unique=False)
    op.create_index('idx_posts_reactions_count', 'posts', ['reactions_count'], unique=False)
    op.create_index('idx_posts_public_created_at', 'posts', ['is_public', 'created_at'], unique=False)
    op.create_index('idx_posts_hearts_count', 'posts', ['hearts_count'], unique=False)
    op.create_index('idx_posts_engagement_created_at', 'posts', ['hearts_count', 'reactions_count', 'shares_count', 'created_at'], unique=False)
    op.create_index('idx_posts_created_at_desc', 'posts', [sa.text('created_at DESC')], unique=False)
    op.alter_column('posts', 'post_type',
               existing_type=sa.Enum('daily', 'photo', 'spontaneous', name='posttype', schema='public'),
               type_=postgresql.ENUM('daily', 'photo', 'spontaneous', name='posttype'),
               existing_nullable=False,
               existing_server_default=sa.text("'daily'::posttype"))
    op.create_index('idx_follows_status_created_at', 'follows', ['status', 'created_at'], unique=False)
    op.create_index('idx_follows_follower_followed', 'follows', ['follower_id', 'followed_id'], unique=False)
    # ### end Alembic commands ###