"""add_last_feed_view_to_users

Revision ID: 157217b0df0a
Revises: 972c37209dbf
Create Date: 2025-09-14 15:52:50.849317

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '157217b0df0a'
down_revision = '972c37209dbf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'post_type',
               existing_type=postgresql.ENUM('daily', 'photo', 'spontaneous', name='posttype'),
               type_=sa.Enum('daily', 'photo', 'spontaneous', name='posttype', schema='public'),
               existing_nullable=False,
               existing_server_default=sa.text("'daily'::posttype"))
    
    # Add last_feed_view column to users table
    op.add_column('users', sa.Column('last_feed_view', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_users_last_feed_view', 'users', ['last_feed_view'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove last_feed_view column from users table
    op.drop_index('ix_users_last_feed_view', 'users')
    op.drop_column('users', 'last_feed_view')
    
    op.alter_column('posts', 'post_type',
               existing_type=sa.Enum('daily', 'photo', 'spontaneous', name='posttype', schema='public'),
               type_=postgresql.ENUM('daily', 'photo', 'spontaneous', name='posttype'),
               existing_nullable=False,
               existing_server_default=sa.text("'daily'::posttype"))
    # ### end Alembic commands ###