"""Refactor EmojiReaction to polymorphic

Revision ID: 3c3ad964c4be
Revises: c642f475eb6d
Create Date: 2026-04-24 15:22:52.547374

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c3ad964c4be'
down_revision = 'c642f475eb6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Execute emoji_reactions schema updates
    sa.Enum('post', 'image', 'comment', name='objecttype').create(op.get_bind())
    op.add_column('emoji_reactions', sa.Column('object_type', sa.Enum('post', 'image', 'comment', name='objecttype'), server_default='post', nullable=False))
    op.add_column('emoji_reactions', sa.Column('object_id', sa.String(), nullable=True))
    op.drop_constraint('unique_user_post_reaction', 'emoji_reactions', type_='unique')
    op.create_index('idx_emoji_reactions_post_object', 'emoji_reactions', ['post_id', 'object_type', 'object_id'], unique=False)
    op.create_unique_constraint('unique_user_object_reaction', 'emoji_reactions', ['user_id', 'object_type', 'object_id'])
    
    # Backfill object_id with post_id for all existing post reactions
    op.execute("UPDATE emoji_reactions SET object_id = post_id WHERE object_id IS NULL AND object_type = 'post'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_object_reaction', 'emoji_reactions', type_='unique')
    op.drop_index('idx_emoji_reactions_post_object', table_name='emoji_reactions')
    op.create_unique_constraint('unique_user_post_reaction', 'emoji_reactions', ['user_id', 'post_id'])
    op.drop_column('emoji_reactions', 'object_id')
    op.drop_column('emoji_reactions', 'object_type')
    sa.Enum('post', 'image', 'comment', name='objecttype').drop(op.get_bind())
    # ### end Alembic commands ###