"""add_mentions_table

Revision ID: 667bf4bdc252
Revises: c0948b20b43e
Create Date: 2025-08-28 11:34:07.978804

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '667bf4bdc252'
down_revision = 'c0948b20b43e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('mentioned_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mentioned_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'mentioned_user_id', name='unique_post_mentioned_user')
    )
    
    # Create indexes for performance
    op.create_index('idx_mentions_mentioned_user_id', 'mentions', ['mentioned_user_id'])
    op.create_index('idx_mentions_post_id', 'mentions', ['post_id'])
    op.create_index('idx_mentions_author_id', 'mentions', ['author_id'])
    op.alter_column('posts', 'post_type',
               existing_type=postgresql.ENUM('daily', 'photo', 'spontaneous', name='posttype'),
               type_=sa.Enum('daily', 'photo', 'spontaneous', name='posttype', schema='public'),
               existing_nullable=False,
               existing_server_default=sa.text("'daily'::posttype"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes
    op.drop_index('idx_mentions_author_id', table_name='mentions')
    op.drop_index('idx_mentions_post_id', table_name='mentions')
    op.drop_index('idx_mentions_mentioned_user_id', table_name='mentions')
    
    op.alter_column('posts', 'post_type',
               existing_type=sa.Enum('daily', 'photo', 'spontaneous', name='posttype', schema='public'),
               type_=postgresql.ENUM('daily', 'photo', 'spontaneous', name='posttype'),
               existing_nullable=False,
               existing_server_default=sa.text("'daily'::posttype"))
    op.drop_table('mentions')
    # ### end Alembic commands ###