"""Add user_interactions table for preference tracking

Revision ID: 8551c0101b00
Revises: 157217b0df0a
Create Date: 2025-09-14 19:35:27.205442

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8551c0101b00'
down_revision = '157217b0df0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_interactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=False),
    sa.Column('interaction_type', sa.String(length=20), nullable=False),
    sa.Column('post_id', sa.String(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_interactions_created_at', 'user_interactions', ['created_at'], unique=False)
    op.create_index('idx_user_interactions_target_user_id', 'user_interactions', ['target_user_id'], unique=False)
    op.create_index('idx_user_interactions_type', 'user_interactions', ['interaction_type'], unique=False)
    op.create_index('idx_user_interactions_user_id', 'user_interactions', ['user_id'], unique=False)
    op.create_index('idx_user_interactions_user_target', 'user_interactions', ['user_id', 'target_user_id'], unique=False)
    op.create_index('idx_user_interactions_user_type', 'user_interactions', ['user_id', 'interaction_type'], unique=False)
    
    op.alter_column('posts', 'post_type',
               existing_type=postgresql.ENUM('daily', 'photo', 'spontaneous', name='posttype'),
               type_=sa.Enum('daily', 'photo', 'spontaneous', name='posttype', schema='public'),
               existing_nullable=False,
               existing_server_default=sa.text("'daily'::posttype"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'post_type',
               existing_type=sa.Enum('daily', 'photo', 'spontaneous', name='posttype', schema='public'),
               type_=postgresql.ENUM('daily', 'photo', 'spontaneous', name='posttype'),
               existing_nullable=False,
               existing_server_default=sa.text("'daily'::posttype"))
    
    op.drop_index('idx_user_interactions_user_type', table_name='user_interactions')
    op.drop_index('idx_user_interactions_user_target', table_name='user_interactions')
    op.drop_index('idx_user_interactions_user_id', table_name='user_interactions')
    op.drop_index('idx_user_interactions_type', table_name='user_interactions')
    op.drop_index('idx_user_interactions_target_user_id', table_name='user_interactions')
    op.drop_index('idx_user_interactions_created_at', table_name='user_interactions')
    op.drop_table('user_interactions')
    # ### end Alembic commands ###