"""Add image_hashes table for deduplication system

Revision ID: 8ae24ef9616d
Revises: bd5b92dd6917
Create Date: 2025-09-29 19:25:45.711425

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ae24ef9616d'
down_revision = 'bd5b92dd6917'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_hashes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('perceptual_hash', sa.String(length=16), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('reference_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('upload_context', sa.String(length=50), nullable=True),
    sa.Column('first_uploader_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash')
    )
    op.create_index(op.f('ix_image_hashes_file_hash'), 'image_hashes', ['file_hash'], unique=False)
    op.create_index(op.f('ix_image_hashes_id'), 'image_hashes', ['id'], unique=False)
    op.create_index(op.f('ix_image_hashes_is_active'), 'image_hashes', ['is_active'], unique=False)
    op.create_index(op.f('ix_image_hashes_perceptual_hash'), 'image_hashes', ['perceptual_hash'], unique=False)
    op.create_index(op.f('ix_image_hashes_upload_context'), 'image_hashes', ['upload_context'], unique=False)
    
    op.alter_column('posts', 'post_type',
               existing_type=postgresql.ENUM('daily', 'photo', 'spontaneous', name='posttype'),
               type_=sa.Enum('daily', 'photo', 'spontaneous', name='posttype', schema='public'),
               existing_nullable=False,
               existing_server_default=sa.text("'daily'::posttype"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'post_type',
               existing_type=sa.Enum('daily', 'photo', 'spontaneous', name='posttype', schema='public'),
               type_=postgresql.ENUM('daily', 'photo', 'spontaneous', name='posttype'),
               existing_nullable=False,
               existing_server_default=sa.text("'daily'::posttype"))
    
    op.drop_index(op.f('ix_image_hashes_upload_context'), table_name='image_hashes')
    op.drop_index(op.f('ix_image_hashes_perceptual_hash'), table_name='image_hashes')
    op.drop_index(op.f('ix_image_hashes_is_active'), table_name='image_hashes')
    op.drop_index(op.f('ix_image_hashes_id'), table_name='image_hashes')
    op.drop_index(op.f('ix_image_hashes_file_hash'), table_name='image_hashes')
    op.drop_table('image_hashes')
    # ### end Alembic commands ###