"""add_rich_content_to_posts

Revision ID: c2d080a29fc5
Revises: ce19c8609c8f
Create Date: 2025-09-06 21:36:17.450647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c2d080a29fc5'
down_revision = 'ce19c8609c8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'post_type',
               existing_type=postgresql.ENUM('daily', 'photo', 'spontaneous', name='posttype'),
               type_=sa.Enum('daily', 'photo', 'spontaneous', name='posttype', schema='public'),
               existing_nullable=False,
               existing_server_default=sa.text("'daily'::posttype"))
    op.alter_column('posts', 'location_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'location_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('posts', 'post_type',
               existing_type=sa.Enum('daily', 'photo', 'spontaneous', name='posttype', schema='public'),
               type_=postgresql.ENUM('daily', 'photo', 'spontaneous', name='posttype'),
               existing_nullable=False,
               existing_server_default=sa.text("'daily'::posttype"))
    # ### end Alembic commands ###