"""drop hearts_count

Revision ID: c642f475eb6d
Revises: f5d3b0e7a2c1
Create Date: 2026-04-07 18:49:42.933591

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c642f475eb6d'
down_revision = 'f5d3b0e7a2c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'hearts_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('hearts_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
    # ### end Alembic commands ###