"""Fix shares table recipient_user_ids column type

Revision ID: d3cd51afbd09
Revises: 5d2fa1a90406
Create Date: 2025-08-27 19:05:20.041231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd3cd51afbd09'
down_revision = '5d2fa1a90406'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'post_type',
               existing_type=postgresql.ENUM('daily', 'photo', 'spontaneous', name='posttype'),
               type_=sa.Enum('daily', 'photo', 'spontaneous', name='posttype', schema='public'),
               existing_nullable=False,
               existing_server_default=sa.text("'daily'::posttype"))
    op.drop_index('idx_shares_created_at', table_name='shares')
    op.drop_index('idx_shares_post_id', table_name='shares')
    op.drop_index('idx_shares_share_method', table_name='shares')
    op.drop_index('idx_shares_user_id', table_name='shares')
    op.drop_constraint('shares_user_id_fkey', 'shares', type_='foreignkey')
    op.drop_constraint('shares_post_id_fkey', 'shares', type_='foreignkey')
    op.create_foreign_key(None, 'shares', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'shares', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shares', type_='foreignkey')
    op.drop_constraint(None, 'shares', type_='foreignkey')
    op.create_foreign_key('shares_post_id_fkey', 'shares', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('shares_user_id_fkey', 'shares', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_shares_user_id', 'shares', ['user_id'], unique=False)
    op.create_index('idx_shares_share_method', 'shares', ['share_method'], unique=False)
    op.create_index('idx_shares_post_id', 'shares', ['post_id'], unique=False)
    op.create_index('idx_shares_created_at', 'shares', ['created_at'], unique=False)
    op.alter_column('posts', 'post_type',
               existing_type=sa.Enum('daily', 'photo', 'spontaneous', name='posttype', schema='public'),
               type_=postgresql.ENUM('daily', 'photo', 'spontaneous', name='posttype'),
               existing_nullable=False,
               existing_server_default=sa.text("'daily'::posttype"))
    # ### end Alembic commands ###