"""add_location_field_to_users

Revision ID: e2c1d9ebe940
Revises: 009_add_enhanced_profile_fields
Create Date: 2025-08-31 12:48:33.909235

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e2c1d9ebe940'
down_revision = '009_add_enhanced_profile_fields'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_follows_created_at', table_name='follows')
    op.drop_index('idx_follows_followed_id', table_name='follows')
    op.drop_index('idx_follows_follower_followed', table_name='follows')
    op.drop_index('idx_follows_follower_id', table_name='follows')
    op.drop_index('idx_follows_status', table_name='follows')
    op.alter_column('posts', 'post_type',
               existing_type=postgresql.ENUM('daily', 'photo', 'spontaneous', name='posttype'),
               type_=sa.Enum('daily', 'photo', 'spontaneous', name='posttype', schema='public'),
               existing_nullable=False,
               existing_server_default=sa.text("'daily'::posttype"))
    op.drop_index('idx_posts_author_created_desc', table_name='posts')
    op.drop_index('idx_posts_created_at_desc', table_name='posts')
    op.drop_index('idx_posts_engagement', table_name='posts')
    op.add_column('users', sa.Column('location', sa.JSON(), nullable=True))
    op.alter_column('users', 'institutions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('users', 'websites',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('users', 'profile_preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('idx_users_city', table_name='users')
    op.drop_index('idx_users_display_name', table_name='users')
    op.drop_index('idx_users_profile_photo_filename', table_name='users')
    op.create_index(op.f('ix_users_city'), 'users', ['city'], unique=False)
    op.create_index(op.f('ix_users_display_name'), 'users', ['display_name'], unique=False)
    op.create_index(op.f('ix_users_profile_photo_filename'), 'users', ['profile_photo_filename'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_profile_photo_filename'), table_name='users')
    op.drop_index(op.f('ix_users_display_name'), table_name='users')
    op.drop_index(op.f('ix_users_city'), table_name='users')
    op.create_index('idx_users_profile_photo_filename', 'users', ['profile_photo_filename'], unique=False)
    op.create_index('idx_users_display_name', 'users', ['display_name'], unique=False)
    op.create_index('idx_users_city', 'users', ['city'], unique=False)
    op.alter_column('users', 'profile_preferences',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('users', 'websites',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('users', 'institutions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('users', 'location')
    op.create_index('idx_posts_engagement', 'posts', ['hearts_count', 'reactions_count', 'shares_count'], unique=False)
    op.create_index('idx_posts_created_at_desc', 'posts', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_posts_author_created_desc', 'posts', ['author_id', sa.text('created_at DESC')], unique=False)
    op.alter_column('posts', 'post_type',
               existing_type=sa.Enum('daily', 'photo', 'spontaneous', name='posttype', schema='public'),
               type_=postgresql.ENUM('daily', 'photo', 'spontaneous', name='posttype'),
               existing_nullable=False,
               existing_server_default=sa.text("'daily'::posttype"))
    op.create_index('idx_follows_status', 'follows', ['status'], unique=False)
    op.create_index('idx_follows_follower_id', 'follows', ['follower_id'], unique=False)
    op.create_index('idx_follows_follower_followed', 'follows', ['follower_id', 'followed_id'], unique=False)
    op.create_index('idx_follows_followed_id', 'follows', ['followed_id'], unique=False)
    op.create_index('idx_follows_created_at', 'follows', ['created_at'], unique=False)
    # ### end Alembic commands ###