"""remove_can_view_post_function

The visibility logic is now generated by ``feed_visibility_sql.build_visibility_sql()``
and ``PostPrivacyService.visible_to_user_clause()``.  The PostgreSQL function was
opaque to the planner, causing 1.2–3.6× slower feed queries with 12–179× more
buffer access.

Revision ID: e7b1a2c3d4f5
Revises: b7f2a6c9d1e3
Create Date: 2026-07-01 23:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e7b1a2c3d4f5"
down_revision = "b7f2a6c9d1e3"
branch_labels = None
depends_on = None


HARDENED_FUNCTION = """
CREATE OR REPLACE FUNCTION can_view_post(p_viewer_id integer, p_post_id uuid)
RETURNS boolean
LANGUAGE SQL
STABLE
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM posts p
        WHERE p.id = p_post_id::text
          AND (
            p.author_id = p_viewer_id
            OR p.privacy_level = 'public'
            OR (
                p.privacy_level = 'custom'
                AND (
                    (
                        EXISTS (
                            SELECT 1
                            FROM post_privacy_rules r
                            WHERE r.post_id = p.id
                              AND r.rule_type = 'followers'
                        )
                        AND EXISTS (
                            SELECT 1
                            FROM follows f
                            WHERE f.follower_id = p_viewer_id
                              AND f.followed_id = p.author_id
                              AND f.status = 'active'
                        )
                    )
                    OR (
                        EXISTS (
                            SELECT 1
                            FROM post_privacy_rules r
                            WHERE r.post_id = p.id
                              AND r.rule_type = 'following'
                        )
                        AND EXISTS (
                            SELECT 1
                            FROM follows f
                            WHERE f.follower_id = p.author_id
                              AND f.followed_id = p_viewer_id
                              AND f.status = 'active'
                        )
                    )
                    OR EXISTS (
                        SELECT 1
                        FROM post_privacy_users pu
                        WHERE pu.post_id = p.id
                          AND pu.user_id = p_viewer_id
                    )
                )
            )
          )
    );
$$;
"""


def upgrade() -> None:
    connection = op.get_bind()
    if connection.dialect.name != "postgresql":
        return

    op.execute(sa.text("DROP FUNCTION IF EXISTS can_view_post(integer, uuid);"))


def downgrade() -> None:
    connection = op.get_bind()
    if connection.dialect.name != "postgresql":
        return

    op.execute(sa.text(HARDENED_FUNCTION))
