"""create_follows_table

Revision ID: e9389cc73d7e
Revises: 667bf4bdc252
Create Date: 2025-08-29 12:34:22.588695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e9389cc73d7e'
down_revision = '667bf4bdc252'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_mentions_author_id', table_name='mentions')
    op.drop_index('idx_mentions_mentioned_user_id', table_name='mentions')
    op.drop_index('idx_mentions_post_id', table_name='mentions')
    op.drop_constraint('mentions_post_id_fkey', 'mentions', type_='foreignkey')
    op.drop_constraint('mentions_mentioned_user_id_fkey', 'mentions', type_='foreignkey')
    op.drop_constraint('mentions_author_id_fkey', 'mentions', type_='foreignkey')
    op.create_foreign_key(None, 'mentions', 'users', ['mentioned_user_id'], ['id'])
    op.create_foreign_key(None, 'mentions', 'users', ['author_id'], ['id'])
    op.create_foreign_key(None, 'mentions', 'posts', ['post_id'], ['id'])
    op.alter_column('posts', 'post_type',
               existing_type=postgresql.ENUM('daily', 'photo', 'spontaneous', name='posttype'),
               type_=sa.Enum('daily', 'photo', 'spontaneous', name='posttype', schema='public'),
               existing_nullable=False,
               existing_server_default=sa.text("'daily'::posttype"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'post_type',
               existing_type=sa.Enum('daily', 'photo', 'spontaneous', name='posttype', schema='public'),
               type_=postgresql.ENUM('daily', 'photo', 'spontaneous', name='posttype'),
               existing_nullable=False,
               existing_server_default=sa.text("'daily'::posttype"))
    op.drop_constraint(None, 'mentions', type_='foreignkey')
    op.drop_constraint(None, 'mentions', type_='foreignkey')
    op.drop_constraint(None, 'mentions', type_='foreignkey')
    op.create_foreign_key('mentions_author_id_fkey', 'mentions', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('mentions_mentioned_user_id_fkey', 'mentions', 'users', ['mentioned_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('mentions_post_id_fkey', 'mentions', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_mentions_post_id', 'mentions', ['post_id'], unique=False)
    op.create_index('idx_mentions_mentioned_user_id', 'mentions', ['mentioned_user_id'], unique=False)
    op.create_index('idx_mentions_author_id', 'mentions', ['author_id'], unique=False)
    # ### end Alembic commands ###