[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
startCommand = "sh -c 'echo Starting deployment... && echo DATABASE_URL: ${DATABASE_URL:0:50} && echo PORT: ${PORT:-8000} && echo Running migrations... && alembic upgrade head && echo Starting server... && uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000} --workers 1'"